name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.24.1
      - run: make build
      - run: go version
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: build
          path: ./handler.zip
  deploy_dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.24.1
      - uses: actions/download-artifact@v4.3.0
        with:
          name: build
      - uses: pulumi/actions@v4
      - run: ls handler.zip
      - run: cd infrastructure && pulumi login ${{ secrets.PULUMI_CLOUD_URL }} && cd ..
      - run: cd infrastructure && pulumi up --stack dev --non-interactive --yes && cd ..
    env:
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-west-2"
