name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.23
      - run: make build
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: build
          path: ./build/handler.zip
  deploy_dev:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4.3.0
        with:
          name: build
      - uses: pulumi/actions@v4
      - run: cd infrastructure && pulumi login ${{ secrets.PULUMI_CLOUD_URL }} && cd ..
      - run: cd infrastructure && pulumi preview --stack dev --non-interactive --expect-no-changes && cd ..

