name: Pull Request Workflow

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      stack: dev
      environment: dev
      run-deploy: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
